name: Cron Snapshots

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger batch ingest
        env:
          BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          CRON_TOKEN: ${{ secrets.CRON_TOKEN }}
          VERCEL_BYPASS_TOKEN: ${{ secrets.VERCEL_BYPASS_TOKEN }}
        run: |
          curl -sS -H "x-vercel-protection-bypass: ${VERCEL_BYPASS_TOKEN}" "${BASE_URL}/api/defi/pools/history/ingest/cron?token=${CRON_TOKEN}"
