name: smoke

on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run smoke tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: bash scripts/ops/smoke.sh
